# Generated by Django 6.0.6 on 2026-06-22 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('file_size', models.IntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_uuid', models.CharField(max_length=255)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('computer_name', models.CharField(blank=True, max_length=255)),
                ('windows_username', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy'), ('ERROR', 'Error')], default='OFFLINE', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('device_uuid', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copies', models.IntegerField(default=1)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('LETTER', 'Letter'), ('LEGAL', 'Legal')], default='A4', max_length=10)),
                ('orientation', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape')], default='PORTRAIT', max_length=10)),
                ('color_mode', models.CharField(choices=[('COLOR', 'Color'), ('MONO', 'Black & White')], default='MONO', max_length=10)),
                ('duplex', models.CharField(choices=[('SIMPLEX', 'Single Side'), ('DUPLEX', 'Double Side')], default='SIMPLEX', max_length=10)),
                ('page_range', models.CharField(blank=True, max_length=50)),
                ('quality', models.CharField(choices=[('DRAFT', 'Draft'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADED', 'Downloaded'), ('PRINTING', 'Printing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='core.document')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='core.printer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
